version: '3.6'
services:
  sam-app:
    build: .
    command: ["$PWD"]
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
