AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A sample AWS Lambda Function

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs10.x

Resources:
  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.lambda
      CodeUri: ./app
      Events:
        ThumbnailApi:
          Type: Api
          Properties:
            Path: /{value}
            Method: get
